madhouse/madhouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

madhouse/main/urls.py
from django.urls import path

from .views import example_page, index, service_page, certificate_page

app_name = 'main'

urlpatterns = [
    path('', index, name='indexpage'),
    path('certificate/<int:certificate_id>', certificate_page, name='certificate_page'),
    path('examples/<int:example_id>', example_page, name='example_page'),
    path('services/<int:service_id>', service_page, name='service_page'),
]

madhouse/main/models.py
from datetime import date

from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class SignUp(models.Model):
    created_at = models.DateTimeField(
        'Дата/время создания',
        auto_now_add=True,
    )
    name = models.CharField(
        'Имя пользователя',
        max_length=255,
    )
    phone_number = PhoneNumberField(
        'Телефон пользователя',
    )
    message = models.TextField(
        'Сообщение',
        null=True,
        blank=True,
    )

    class Meta:
        ordering = [
            '-id',
        ]
        verbose_name = 'Обращения'
        verbose_name_plural = 'Обращения'

    def __str__(self):
        return f'Заявка от {self.name}'


class MainData(models.Model):
    title = models.CharField(
        'Нзвание организации',
        max_length=255,
    )
    about_us = models.TextField(
        'О нас',
    )
    vk = models.CharField(
        'Ссылка на ВКонтакте',
        max_length=255,
    )
    instagram = models.CharField(
        'Ссылка на Инстаграмм',
        max_length=255,
    )
    telegram = models.CharField(
        'Ссылка на Телеграм',
        max_length=255,
    )
    whatsapp = models.CharField(
        'Ссылка на WhatsApp',
        max_length=255,
    )
    phone = PhoneNumberField(
        'Номер для связи',
    )
    adress = models.CharField(
        'Адрес',
        max_length=255,
    )

    class Meta:
        verbose_name = 'Основные данные'
        verbose_name_plural = 'Основные данные'

    def __str__(self):
        return self.title


class Certificate(models.Model):
    certificate = models.ForeignKey(
        'MainData',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Связь с основными данными',
        help_text='Обязательно выбирать',
    )
    name = models.CharField(
        'Название сертификата',
        max_length=255,
    )
    description = models.TextField(
        'Описание сертификата',
    )
    image = models.ImageField(
        'Изображение',
        upload_to='certificates',
        help_text='Размер изображений: 700x700',
    )

    class Meta:
        verbose_name = 'Сертификат'
        verbose_name_plural = 'Сертификаты'

    def __str__(self):
        return self.name


class Service(models.Model):
    service = models.ForeignKey(
        'MainData',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Связь с основными данными',
        help_text='Обязательно выбирать',
    )
    name = models.CharField(
        'Название услуги',
        max_length=255,
    )
    description = models.TextField(
        'Описание услуги',
    )
    image = models.ImageField(
        'Изображение',
        upload_to='services',
        help_text='Размер изображений: 700x700',
    )

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    def __str__(self):
        return self.name


class ServiceExample(models.Model):
    service_example = models.ForeignKey(
        'MainData',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Связь с основными данными',
        help_text='Обязательно выбирать',
    )
    created_at = models.DateField(
        'Дата оказания услуги',
        default=date.today,
    )
    title = models.CharField(
        'Заголовок',
        max_length=255,
    )
    content = models.TextField(
        'Описание',
    )
    client = models.CharField(
        'Клиент',
        max_length=255,
    )
    service_type = models.CharField(
        'Тип услуги',
        max_length=255,
    )
    image = models.ImageField(
        'Изображение',
        upload_to='examples',
        help_text='Размер изображений: 700x467',
    )

    class Meta:
        verbose_name = 'Пример работы'
        verbose_name_plural = 'Примеры работ'

    def __str__(self):
        return self.title

madhouse/main/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

from .models import SignUp
from .validations import spam_validator, username_at_russian_alphabet


class SignUpForm(forms.ModelForm):
    reCAPTCHA = ReCaptchaField(
        label='',
        widget=ReCaptchaV2Checkbox(
            attrs={
                'data-size': 'compact',
            }
        ),
    )
    nickname = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'style': 'display:none;',
            }
        ),
        required=False,
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Ваш телефон',
                'type': 'text',
            }
        )
    )

    class Meta:
        model = SignUp
        fields = (
            'name',
            'phone_number',
            'message',
            'nickname',
        )
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ваше имя',
                }
            ),
            'message': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ваше сообщение',
                }
            ),
        }

    def save(self, commit=True):
        self.cleaned_data.pop('reCAPTCHA', None)
        return super().save(commit=commit)

    def clean_name(self):
        data = self.cleaned_data.get('name')
        username_at_russian_alphabet(data)
        return data

    def clean_nickname(self):
        data = self.cleaned_data.get('nickname')
        if data:
            raise forms.ValidationError(
                'Введено недопустимое значение, попробуйте другое.'
            )
        return data

    def clean_text(self):
        data = self.cleaned_data.get('text')
        spam_validator(data)
        return data

madhouse/main/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render

from .forms import SignUpForm
from .models import MainData, Service, ServiceExample, Certificate
from .utils import generate_error_messages, send_telegram_message


def index(request):
    main_data = MainData.objects.first()
    certificates = main_data.certificate_set.all()
    services = main_data.service_set.all()
    examples = main_data.serviceexample_set.all()

    context = {
        'main_data': main_data,
        'certificates': certificates,
        'services': services,
        'examples': examples,
        'form': SignUpForm(),
    }

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

            send_telegram_message.delay(**form.cleaned_data)

            messages.success(
                request=request,
                message=(
                    'Сообщение успешно отправлено! '
                    'В ближайшее время мы с Вами свяжемся.'
                ),
            )
            return render(
                request=request,
                template_name='main.html',
                context=context,
            )
        else:
            generate_error_messages(
                request=request,
                form=form,
            )
            return redirect(f'{request.path}#section-contact')

    return render(
        request=request,
        template_name='main.html',
        context=context,
    )


def certificate_page(request, certificate_id):
    certificate = get_object_or_404(Certificate, id=certificate_id)
    return render(
        request=request,
        template_name='certificate_page.html',
        context={'certificate_page': certificate},
    )


def example_page(request, example_id):
    example = get_object_or_404(ServiceExample, id=example_id)
    return render(
        request=request,
        template_name='example_page.html',
        context={'example_page': example},
    )


def service_page(request, service_id):
    service = get_object_or_404(Service, id=service_id)
    return render(
        request=request,
        template_name='service_page.html',
        context={'service_page': service},
    )

madhouse/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru" dir="ltr">
<html prefix="og: http://ogp.me/ns#" prefix="og: http://ogp.me/ns#">

<head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="MADHOUSE — студия детейлинга" name="description" />
    <meta content="alexpunder" name="author" />

    <meta property="og:locale" content="ru_RU" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://madhouse-detail.ru" />
    <meta property="og:title" content="MADHOUSE — студия детейлинга" />
    <meta property="og:description" content="" />
    <meta property="og:image" content="{% static "images/dark-logo.png" %}" />

    <title>MADHOUSE — студия детейлинга</title>
    <link rel="icon" href="{% static "images/dark-icon.svg" %}" type="image/gif" sizes="16x16">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" id="bootstrap" />
    <link href="{% static "css/plugins.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css" />
    <style>
        :root {
            --primary-color: #CF1F1F;
            --primary-color-rgb: 207, 31, 31;
        }
    </style>
    <link href="{% static "css/coloring.css" %}" rel="stylesheet" type="text/css" />

    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link rel="prefetch" href="https://fonts.gstatic.com/" crossorigin="anonymous">
    <link rel="dns-prefetch" href="https://fonts.googleapis.com/css2?family=Saira:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap">
</head>

<body class="onepage dark-scheme">
    <div id="wrapper">

    {% include "header.html" %}

    {% block content %}
    {% endblock content %}
    
    <a href="" id="back-to-top"></a>
    
    {% include "footer.html" %}

    <script src="{% static "js/plugins.js" %}"></script>
    <script src="{% static "js/designesia.js" %}"></script>
    <script>
    jQuery(document).ready(function() {
        $(function() {
            // jquery typed plugin
            $(".typed").typed({
                stringsElement: $('.typed-strings'),
                typeSpeed: 100,
                backDelay: 500,
                loop: true,
                contentType: 'html', // or text
                // defaults to false for infinite loop
                loopCount: false,
                callback: function() { null; },
                resetCallback: function() { newTyped(); }
            });
        });
    });
    </script>
    <script>
        window.onload = function () {
            const alerts = document.querySelectorAll('.alert');
            alerts.forEach(alert => {
                setTimeout(() => {
                    alert.style.display = 'none';
                }, 5000);
            });
        };
    </script>
</body>

</html>

madhouse/templates/certificate.html
{% load static %}

<div class="bloglist item">
    <div class="post-content">
        <div class="post-image">
            <div class="de_modal" data-url="{% url 'main:certificate_page' certificate_id=certificate.id %}"><img alt="" src="{{ certificate.image.url }}" class="lazy grayscale"></div>
        </div>
        <div class="post-text">
            <h4 class="de_modal" data-url="{% url 'main:certificate_page' certificate_id=certificate.id %}">{{ certificate.name }}</h4>
        </div>
    </div>
</div>

madhouse/templates/certificate_page.html
{% load static %}

<div id="de_modal-content" class="container">
    <div class="row g-5">
        <div class="col-lg-8">
            <img src="{{ certificate_page.image.url }}" alt="" class="img-fluid">
        </div>

        <div class="col-lg-4 de_project-info">
            <h3>{{ certificate_page.name }}</h3>
            <p>{{ certificate_page.description }}</p>
        </div>
    </div>
</div>

madhouse/templates/example.html
{% load static %}

<div class="bloglist item">
    <div class="post-content">
        <div class="post-image">
            <div class="de_modal" data-url="{% url 'main:example_page' example_id=example.id %}"><img alt="" src="{{ example.image.url }}" class="lazy grayscale"></div>
        </div>
        <div class="post-text">
            <h4 class="de_modal" data-url="{% url 'main:example_page' example_id=example.id %}">{{ example.title }}</h4>
            <p>{{ example.content|truncatechars:100 }}</p>
        </div>
    </div>
</div>

madhouse/templates/example_page.html
{% load static %}

<div id="de_modal-content" class="container">
    <div class="row g-5">
        <div class="col-lg-8">
            <img src="{{ example_page.image.url }}" alt="" class="img-fluid">
        </div>

        <div class="col-lg-4 de_project-info">
            <h3>{{ example_page.title }}</h3>
            <p>{{ example_page.content }}</p>
           
            <div class="de_project-details">
                <div class="d-field">
                    <i class="fa fa-user-o"></i>Клиент: <span>{{ example_page.client }}</span>
                </div>
                <div class="d-field">
                    <i class="fa fa-file-text-o"></i>Услуга: <span>{{ example_page.service_type }}</span>
                </div>
                <div class="d-field">
                    <i class="fa fa-calendar-o"></i>Дата: <span>{{ example_page.created_at }}</span>
                </div>
            </div>
        </div>
    </div>
</div>

madhouse/templates/footer.html
{% load static %}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <a href="{% url "main:indexpage" %}">
                    <span class="copy">&copy; {{ main_data.title }}, 2023 - {% now "Y" %}</span>
                </a>
            </div>
            <div class="col-md-6">
                <div class="social-icons">
                    <a href="{{ main_data.vk }}" title="vk" target="_blank"><i class="fa fa-vk fa-lg"></i></a>
                    <a href="{{ main_data.instagram }}" title="instagram" target="_blank"><i class="fa fa-instagram fa-lg"></i></a>
                    <a href="{{ main_data.telegram }}" title="telegram" target="_blank"><i class="fa fa-telegram fa-lg"></i></a>
                    <a href="{{ main_data.whatsapp }}" title="whatsapp" target="_blank"><i class="fa fa-whatsapp fa-lg"></i></a>
                </div>
            </div>
        </div>
    </div>
</footer>

madhouse/templates/header.html
{% load static %}

<header class="transparent">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="de-flex sm-pt10">
                    <div class="de-flex-col">
                        <div class="de-flex-col">
                            <div id="logo">
                                <a href="{% url 'main:indexpage' %}">
                                    <img alt="" class="logo" src="{% static "images/dark-logo.svg" %}" width="200" height="80" />
                                    <img alt="" class="logo-2" src="{% static "images/dark-logo.svg" %}" width="200" height="80" />
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="de-flex-col header-col-right">
                        <ul id="mainmenu">
                            <li><a class="active" href="#top">Главная<span></span></a></li>
                            <li><a href="#section-about">О нас<span></span></a></li>
                            <li><a href="#section-services">Услуги<span></span></a></li>
                            <li><a href="#section-examples">Примеры работ<span></span></a></li>
                            <li><a href="#section-contact">Написать нам<span></span></a></li>
                            <li><a href="#section-onmap">На карте<span></span></a></li>
                        </ul>
                        <div class="menu_side_area">
                            <span id="menu-btn"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if messages %}
            <div>
                {% for message in messages %}
                    {% if message.tags == "alert-success" %}
                        <div class="alert {{ message.tags }} text-center alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    </div>
</header>

madhouse/templates/main.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="no-bottom no-top" id="content">
    <div id="top"></div>

    <div id="preloader">
        <div class="preloader1"></div>
    </div>

    <div class="float-text">
        <div class="de_social-icons">
            <a href="{{ main_data.vk }}" title="vk" target="_blank"><i class="fa fa-vk fa-lg"></i></a>
            <a href="{{ main_data.instagram }}" title="instagram" target="_blank"><i class="fa fa-instagram fa-lg"></i></a>
            <a href="{{ main_data.telegram }}" title="telegram" target="_blank"><i class="fa fa-telegram fa-lg"></i></a>
            <a href="{{ main_data.whatsapp }}" title="whatsapp" target="_blank"><i class="fa fa-whatsapp fa-lg"></i></a>
        </div>
        <span>Наши соцсети</span>
    </div>

    <div id="de_modal">
        <button class="button-close"></button>
        <div class="d-modal-loader"></div>
    </div>

    <section aria-label="section" class="jarallax text-light">
        <div class="v-center">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <h6 class="wow fadeInUp" data-wow-delay=".4s"><span class="text-white">{{ main_data.title }}</span></h6>
                        <div class="spacer-10"></div>
                        <div class="h1_big text-white wow fadeInUp" data-wow-delay=".6s">
                            <div class="typed-strings">
                                {% for service in services %}
                                    <p>{{ service.name }}</p>
                                {% endfor %}
                            </div>
                            <div class="typed"></div>
                        </div>
                    </div>
                    <div class="spacer-20"></div>
                    <ul class="list_location wow fadeInUp" data-wow-delay=".8s">
                        <li><span>Россия</span>Волжский, Волгоградская область</li>
                    </ul>
                </div>
            </div>
        </div>
        <a href="#section-about" class="mouse-icon-click scroll-to wow fadeInUp" data-wow-delay=".8s">
            <span class="mouse fadeScroll relative" data-scroll-speed="10">
                <span class="scroll"></span>
            </span>
        </a>
        <div class="de-gradient-edge-bottom"></div>
    </section>

    <section id="section-about">
        <div class="container relative">
            <div class="row">
                <div class="col-md-12 text-center wow fadeInUp">
                    <h2>О нас</h2>
                    <div class="space-border"></div>
                </div>
                <div class="col-md-8 offset-md-2 text-center wow fadeInUp">
                    <p>
                        {{ main_data.about_us }}
                    </p>
                </div>
            </div>
        </div>
        <div class="container relative">
            <div id="carousel-certificate" class="owl-carousel wow fadeInUp">
                {% for certificate in certificates %}
                    {% include "certificate.html" %}
                {% endfor %}
            </div>
        </div>
    </section>

    <section id="section-services">
        <div class="container relative">
            <div class="row">
                <div class="col-md-12 text-center wow fadeInUp">
                    <h2>Услуги</h2>
                    <div class="space-border"></div>
                </div>
            </div>
            <div id="gallery" class="row sequence">
                {% for service in services %}
                    {% include "service.html" %}
                {% endfor %}
            </div>
        </div>
    </section>

    <section id="section-examples">
        <div class="container relative">
            <div class="row">
                <div class="col-md-12 text-center wow fadeInUp">
                    <h2>Примеры Работ</h2>
                    <div class="space-border"></div>
                </div>
            </div>
            <div id="carousel-blog" class="owl-carousel wow fadeInUp">
                {% for example in examples %}
                    {% include "example.html" %}
                {% endfor %}
            </div>
        </div>
    </section>

    <section id="section-contact" class="jarallax">
        <div class="de-gradient-edge-top"></div>
        <div class="container z-index-1000">
            <div class="row">
                <div class="col-md-12 text-center wow fadeInUp">
                    <h2>Написать Нам</h2>
                    <div class="space-border"></div>
                </div>
                {% if messages %}
                    <div>
                        {% for message in messages %}
                            {% if message.tags == "alert-danger" %}
                                <div class="alert {{ message.tags }} text-center alert-dismissible fade show" role="alert">
                                    <strong>{{ message }}</strong>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="col-lg-8 offset-lg-2 wow fadeInUp">
                    <div class="contact_form_wrapper">
                        <form method="post" action="{% url 'main:indexpage' %}" class="form-border">

                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="field-set">
                                        <label for="{{ form.name.id_for_label }}"></label>
                                        {{ form.name }}
                                        {{ form.name.errors }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="field-set">
                                        <label for="{{ form.phone_number.id_for_label }}"></label>
                                        {{ form.phone_number }}
                                        {{ form.phone_number.errors }}
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <div class="field-set">
                                    <label for="{{ form.message.id_for_label }}"></label>
                                    {{ form.message }}
                                    {{ form.message.errors }}
                                </div>
                                <div class="col-auto align-self-center form-group">
                                    <div class="field-set">
                                        <label for="{{ form.reCAPTCHA.id_for_label }}"></label>
                                        {{ form.reCAPTCHA }}
                                        {{ form.reCAPTCHA.errors }}
                                    </div>
                                    <div class="mt10">
                                        <label class="form-check-label" for="notice">
                                            <input class="form-check-input" type="checkbox" id="notice" onchange="document.getElementById('submitcheck').disabled = !this.checked;">
                                            Согласен с обработкой персональных данных
                                        </label>
                                    </div>
                                    <div class="mt10">
                                        <button id="submitcheck" disabled class="btn-main" type="submit">Отправить</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="spacer-double"></div>
                    <div class="row text-center wow fadeInUp">
                        <div class="col-md-4">
                            <div class="wm-1"></div>
                            <h6>Мы ВКонтакте</h6>
                            <p>
                                <a href="{{ main_data.vk }}" title="vk" target="_blank" style="color:#aaaaaa;">{{ main_data.vk|truncatechars:40 }}</a>
                            </p>
                        </div>
                        <div class="col-md-4">
                            <div class="wm-1"></div>
                            <h6>Наш номер</h6>
                            <p>
                                <a href="tel:{{ main_data.phone }}" title="phone" target="_blank" style="color:#aaaaaa;">{{ main_data.phone }}</a>
                            </p>
                        </div>
                        <div class="col-md-4">
                            <div class="wm-1"></div>
                            <h6>Адрес</h6>
                            <p>
                                <a href="https://yandex.ru/maps/-/CDxJb-oI" title="adress_map" target="_blank" style="color:#aaaaaa;">{{ main_data.adress }}</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="de-gradient-edge-bottom"></div>
    </section>

    <section id="section-onmap" class="jarallax" style="padding: 0 0 50px 0;">
        <div class="container relative">
            <div id="section-onmap" class="map-container">
                <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Adbbee6d4e3bd55afd615b40f033140fb3865643baf9ac50db13772afc511e9e5&amp;width=100%25&amp;height=472&amp;lang=ru_RU&amp;scroll=false"></script>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

madhouse/templates/service.html
{% load static %}

<div class="col-md-4 item wow">
    <div class="de_modal" data-url="{% url 'main:service_page' service_id=service.id %}">
        <div class="card-image-1 mod-c" data-tilt>
            <div class="d-text">
                <h3>{{ service.name }}</h3>
            </div>
            <img src="{{ service.image.url }}" class="img-fluid" alt="">
        </div>
    </div>
</div>

madhouse/templates/service_page.html
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="blog-read">
                <img alt="" src="{{ service_page.image.url }}" class="img-fullwidth rounded">
                <h2>{{ service_page.title }}</h2>
                <div class="post-text">
                  <p>{{ service_page.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>